//! CLAUDE.md generator - creates context file from repo analysis

use crate::context::{scanner, token_counter};
use crate::error::Result;
use colored::Colorize;

/// Generate CLAUDE.md from repository analysis
pub async fn run(output: &str, force: bool) -> Result<()> {
    let cwd = std::env::current_dir()?;
    let output_path = cwd.join(output);

    if output_path.exists() && !force {
        println!(
            "{} {} already exists. Use --force to overwrite.",
            "Warning:".yellow(),
            output
        );
        return Ok(());
    }

    println!("{}", "Scanning repository...".cyan());

    // Scan the repository
    let info = scanner::scan_repo(&cwd)?;

    // Generate CLAUDE.md content
    let content = generate_claude_md(&info)?;

    // Count tokens
    let tokens = token_counter::count_tokens(&content)?;

    // Write file
    std::fs::write(&output_path, &content)?;

    println!("{} Generated {} ({} tokens)", "✓".green(), output, tokens);
    println!();
    println!("Detected:");
    println!("  Languages: {}", info.languages.join(", ").cyan());
    if let Some(fw) = &info.framework {
        println!("  Framework: {}", fw.cyan());
    }
    if let Some(tf) = &info.test_framework {
        println!("  Testing: {}", tf.cyan());
    }
    if let Some(linter) = &info.linter {
        println!("  Linting: {}", linter.cyan());
    }

    Ok(())
}

fn generate_claude_md(info: &scanner::ProjectInfo) -> Result<String> {
    let mut content = String::new();

    // Header
    content.push_str(&format!("# CLAUDE.md — {}\n", info.name));
    content.push_str("Generated by `gitintel context init`\n\n");

    // Project Overview
    content.push_str("## Project Overview\n");
    if let Some(desc) = &info.description {
        content.push_str(&format!("{}\n\n", desc));
    } else {
        content.push_str("[Add project description here]\n\n");
    }

    // Tech Stack
    content.push_str("## Tech Stack\n");
    if !info.languages.is_empty() {
        content.push_str(&format!("- **Languages:** {}\n", info.languages.join(", ")));
    }
    if let Some(runtime) = &info.runtime {
        content.push_str(&format!("- **Runtime:** {}\n", runtime));
    }
    if let Some(fw) = &info.framework {
        content.push_str(&format!("- **Framework:** {}\n", fw));
    }
    if let Some(db) = &info.database {
        content.push_str(&format!("- **Database:** {}\n", db));
    }
    if let Some(tf) = &info.test_framework {
        content.push_str(&format!("- **Testing:** {}\n", tf));
    }
    if let Some(linter) = &info.linter {
        content.push_str(&format!("- **Linting:** {}\n", linter));
    }
    content.push('\n');

    // Architecture
    content.push_str("## Architecture\n");
    content.push_str("```\n");
    for dir in &info.structure.root_dirs {
        content.push_str(&format!("├── {}/\n", dir));
    }
    content.push_str("```\n\n");

    if !info.structure.entry_points.is_empty() {
        content.push_str("### Entry Points\n");
        for ep in &info.structure.entry_points {
            content.push_str(&format!("- `{}`\n", ep));
        }
        content.push('\n');
    }

    // Key Conventions
    content.push_str("## Key Conventions\n");
    if let Some(commit_fmt) = &info.conventions.commit_format {
        content.push_str(&format!("- **Commits:** {}\n", commit_fmt));
    } else {
        content.push_str("- **Commits:** [Add commit convention]\n");
    }
    if let Some(style) = &info.conventions.code_style {
        content.push_str(&format!("- **Code Style:** {}\n", style));
    }
    content.push('\n');

    // Dependencies
    if !info.dependencies.is_empty() {
        content.push_str("## Key Dependencies\n");
        for dep in &info.dependencies {
            content.push_str(&format!("- `{}`\n", dep));
        }
        content.push('\n');
    }

    // Common Tasks
    content.push_str("## Common Tasks\n");
    content.push_str("```bash\n");
    if info.languages.iter().any(|l| l.contains("Rust")) {
        content.push_str("# Build\ncargo build\n\n");
        content.push_str("# Test\ncargo test\n\n");
        content.push_str("# Lint\ncargo clippy\n");
    } else if info
        .languages
        .iter()
        .any(|l| l.contains("JavaScript") || l.contains("TypeScript"))
    {
        content.push_str("# Install\nbun install\n\n");
        content.push_str("# Dev\nbun run dev\n\n");
        content.push_str("# Test\nbun test\n\n");
        content.push_str("# Build\nbun run build\n");
    } else if info.languages.iter().any(|l| l.contains("Python")) {
        content.push_str("# Install\npip install -r requirements.txt\n\n");
        content.push_str("# Test\npytest\n");
    } else if info.languages.iter().any(|l| l.contains("Go")) {
        content.push_str("# Build\ngo build\n\n");
        content.push_str("# Test\ngo test ./...\n");
    }
    content.push_str("```\n\n");

    // Critical Files
    content.push_str("## Critical Files\n");
    content.push_str("Files that should be carefully reviewed before modification:\n");
    content.push_str("- [Add critical files here]\n\n");

    // Footer
    content.push_str("---\n");
    content.push_str("*This file was auto-generated by GitIntel. Edit as needed.*\n");

    Ok(content)
}
